### ISSUE TITLE
请问是否能进行自定义歌曲、歌曲谱色、场地BUFF，照片BUFF，活动技能BUFF

### ISSUE THREAD

**Issue by Akisaki2** [MalitsPlus/HoshimiStage#170]
在目前的网页工具内容里面，无法找到跑格子这个活动的任何谱面，在给调试队伍的时候带来一定的困难。

**Comment by MalitsPlus** [comment]
> 自定义歌曲、歌曲谱色、场地BUFF

项目初期有考虑过，像 [这个](https://ip.outv.im/notemap) 一样。但考虑到自己选颜色太麻烦于是做成了现在这样选任务的形式。尤其是场地 buff 数量非常多，要实现的话恐怕还得加一个场地 buff filter 才能有实用价值。


> 活动技能
和场地 buff 一样数量太多实现起来太复杂，于是舍弃掉了。

另外带活动技能的 Live 都是可以多次挑战的，配合最近官方出的 Live 分析功能应该会更好用。


> 照片BUFF

在考虑实装这个机能 ~~（咕~~ 


> 无法找到跑格子这个活动的任何谱面

确实有一部分个人认为价值不大的活动曲目被排除掉了，需要的话我可以加一个其他类型把所有被排除的曲目都放进来，虽然这样一大堆混在一起可能不太好找到想要选择的曲目。

**Comment by Akisaki2** [comment]
> > 自定义歌曲、歌曲谱色、现场BUFF
> 
> 项目刚有考虑过，像[这个](https://ip.outv.im/notemap)一样。但考虑到自己选颜色太麻烦于是就成了现在这样选任务的形式。尤其是场地buff数量非常多，要实现的事情恐怕还得加一个场地buff过滤器才能有实用价值。
> 
> > 活动技能
> 
> 和现场buff同样数量实现起来太复杂，于是舍弃了。 另外带活动技能的Live都是可以多重挑战的，配合最近官方出的Live分析功能应该会更好用。
> 
> > 照片BUFF
> 
> 在考虑实装这个机器的能力~（咕~
> 
> > 无法找到跑格子这个活动的任何谱面
> 
> 确实有一部分个人认为价值不大的活动轨迹被修复掉了，需要的话我可以添加一个其他类型把所有被修复的轨迹都放进去，虽然这么一大堆混在一起可能不太好找到想要的选择曲目。

作者现在已经不更新演示了么）
最近想测试下阵容然后发现已经没有演示模块了..

**Comment by MalitsPlus** [comment]
> 作者现在已经不更新演示了么） 最近想测试下阵容然后发现已经没有演示模块了..

是的，模拟 Live 功能已经停止开发了，因为情报不足而且官方自己已经搞出了一个很优秀的分析功能。
模拟 Live 功能目前仍然可以通过显式指示路径访问（https://ipr.vibbit.me/notemap），但其结果已经不可靠。

**Comment by Akisaki2** [comment]
> > 作者现在已经不更新演示了么） 最近想测试下阵容然后发现已经没有演示模块了..
> 
> 是的，模拟 Live 功能已经停止开发了，因为情报不足而且官方自己已经搞出了一个很优秀的分析功能。 模拟 Live 功能目前仍然可以通过显式指示路径访问（ https://ipr.vibbit.me/notemap ），但其结果已经不可靠。

好的，感谢作者的辛苦付出
现在图鉴也很好用，筛选也是我比较需要的功能，非常感谢！
